/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BoutiqueRouteImport } from './routes/boutique'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ContactTelephoneRouteImport } from './routes/contact/telephone'
import { Route as ContactInstallationRouteImport } from './routes/contact/installation'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueRoute = BoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContactRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactTelephoneRoute = ContactTelephoneRouteImport.update({
  id: '/telephone',
  path: '/telephone',
  getParentRoute: () => ContactRoute,
} as any)
const ContactInstallationRoute = ContactInstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => ContactRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boutique': typeof BoutiqueRoute
  '/contact': typeof ContactRouteWithChildren
  '/contact/installation': typeof ContactInstallationRoute
  '/contact/telephone': typeof ContactTelephoneRoute
  '/product/$id': typeof ProductIdRoute
  '/contact/': typeof ContactIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boutique': typeof BoutiqueRoute
  '/contact/installation': typeof ContactInstallationRoute
  '/contact/telephone': typeof ContactTelephoneRoute
  '/product/$id': typeof ProductIdRoute
  '/contact': typeof ContactIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boutique': typeof BoutiqueRoute
  '/contact': typeof ContactRouteWithChildren
  '/contact/installation': typeof ContactInstallationRoute
  '/contact/telephone': typeof ContactTelephoneRoute
  '/product/$id': typeof ProductIdRoute
  '/contact/': typeof ContactIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boutique'
    | '/contact'
    | '/contact/installation'
    | '/contact/telephone'
    | '/product/$id'
    | '/contact/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boutique'
    | '/contact/installation'
    | '/contact/telephone'
    | '/product/$id'
    | '/contact'
  id:
    | '__root__'
    | '/'
    | '/boutique'
    | '/contact'
    | '/contact/installation'
    | '/contact/telephone'
    | '/product/$id'
    | '/contact/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoutiqueRoute: typeof BoutiqueRoute
  ContactRoute: typeof ContactRouteWithChildren
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique': {
      id: '/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof BoutiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof ContactRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/telephone': {
      id: '/contact/telephone'
      path: '/telephone'
      fullPath: '/contact/telephone'
      preLoaderRoute: typeof ContactTelephoneRouteImport
      parentRoute: typeof ContactRoute
    }
    '/contact/installation': {
      id: '/contact/installation'
      path: '/installation'
      fullPath: '/contact/installation'
      preLoaderRoute: typeof ContactInstallationRouteImport
      parentRoute: typeof ContactRoute
    }
  }
}

interface ContactRouteChildren {
  ContactInstallationRoute: typeof ContactInstallationRoute
  ContactTelephoneRoute: typeof ContactTelephoneRoute
  ContactIndexRoute: typeof ContactIndexRoute
}

const ContactRouteChildren: ContactRouteChildren = {
  ContactInstallationRoute: ContactInstallationRoute,
  ContactTelephoneRoute: ContactTelephoneRoute,
  ContactIndexRoute: ContactIndexRoute,
}

const ContactRouteWithChildren =
  ContactRoute._addFileChildren(ContactRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoutiqueRoute: BoutiqueRoute,
  ContactRoute: ContactRouteWithChildren,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
